### ISSUE TITLE
re-run envelope results without min and max temps

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/vin#38]
Use same code as for deleting the precip ... but leave in precip and delete the min and max temperatures

**Comment by lizzieinvancouver** [comment]
Lizzie's note to self: We still do this with 75% of variables.

**Comment by MoralesCastilla** [comment]
I have done this now, and repeated Fig. 3 (i.e. gains/losses for each cultivar) according to results excluding temps. I think this should do, but I can repeat Fig 2 as well, if needed. f482ddb06c4c32c523cfb42ea3f45e0360431a68

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Great! I think we need consistent figures for the no precip and no max/min temps, so I think we also need to repeat Fig 2 for the no max/min temps as well. We'll want to be able to make an equal sentence to the one we have for precip, which is:
`Including precipitation in our predictions, however, did have an important moderating effect: loss estimates when we excluded precipitation variables (i.e., used veraison-maturity models based on temperature variables alone) were higher and showed a reduced ability of cultivar turnover to buffer regions from such losses (Figs. \ref{fig:tempbasedturnover}-\ref{fig:tempbasedturnoverglob}). `

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver 
I have included the version of Fig.2 without temps as well (baedc86faa80e4f5bd7b64faf9f315c849a18d8d).
The text could read along the lines:

`Both minimum and maximum temperatures had a noticeable effect on our results. Excluding these variables from the computation of maturity climatic envelopes led to a decrease of region loss under both scenarios (see fig. SXXX). Nevertheless, the overall pattern of cultivar diversity decreasing the loss of climatically suitable regions due to climate change, holds.`

**Comment by lizzieinvancouver** [comment]
I just took this out of the main text, because we're over and I was not sure we needed it. But it's in the  supp so I think we can close.
