### ISSUE TITLE
Add when veraison date loss mattered to caption ...

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/vin#52]
of reasons for gains/losses figure in Supp.

**Comment by lizzieinvancouver** [comment]
Can we say 
(1) globally when it mattered to our projections in each (2C, 4C) scenario?
(2) the max it mattered for any one variety? 
And/or add it to that figure (currently S14: Drivers of loss of climatic suitability within current winegrowing regions)

**Comment by MoralesCastilla** [comment]
I have pushed a table /analyses/region_loss/Table.Losses.due2.Ver.shifts.csv (955b2012440ff64cccfcdfff6a88e93629209038) with analyses on the effects of the veraison 275 DOY cut-off on our results, for each variety and each scenario. The proportion of pixels loss (out of the total losses due to both envelope shifts and veraison shifts) due to a variety being projected to reach veraison after DOY 275 is null under 2Cwarming and <2% under 4Cwarming. This should confirm that our results are not affected by the cut-off, right?

**Comment by lizzieinvancouver** [comment]
Done, see e188878afeefc6143192477ed3f1e200165b15da
